/*
SINTAXIS DE LOS TRIGGERS

CREATE TRIGGER (NOMBRE DEL TRIGGER)
ON (NOMBE DE LA TABLA)
FOR || AFTER || INSTEAD OFF (SENTENCIA DONDE SE EJECUTARA)
*/

USE ServicioMedico
GO

SELECT * FROM tbPacientes
SELECT * FROM tbAlumnos
SELECT * FROM tbCarreras
SELECT * FROM tbGeneros
SELECT * FROM tbTiposPacientes

SELECT * FROM tbCategorias
SELECT * FROM tbMedicamentos
SELECT * FROM tbDetallesConsultas
SELECT * FROM tbConsultas