/*
SINTAXIS DE LOS TRIGGERS

CREATE TRIGGER (NOMBRE DEL TRIGGER)
ON (NOMBE DE LA TABLA)
FOR || AFTER || INSTEAD OFF (SENTENCIA DONDE SE EJECUTARA)
*/

USE ServicioMedico
GO

SELECT * FROM tbPacientes
SELECT * FROM tbAlumnos
SELECT * FROM tbCarreras
SELECT * FROM tbGeneros
SELECT * FROM tbTiposPacientes

SELECT * FROM tbConsultas
SELECT * FROM tbMotivosConsultas
SELECT * FROM tbMedicamentosConsultas

ALTER TABLE tbConsultas
ADD
EstatusConsulta SMALLINT,
Temperatura DECIMAL(4,2) NULL, 
TA NVARCHAR(8) NULL,
FC DECIMAL(6,3) NULL, 
FR DECIMAL(6,3) NULL
GO