USE ServicioMedico
GO

IF OBJECT_ID('insAgregarPacientes') IS NOT NULL
DROP PROC insAgregarPacientes
GO

CREATE PROCEDURE insAgregarPacientes
(
@Tipo INT,
@Nombre NVARCHAR(50),
@Genero NVARCHAR(9),
@Retornado BIGINT OUTPUT
)
AS
BEGIN
	IF @Tipo=2 --AGREGAR DATOS DEL DOCENTE
	BEGIN
		INSERT INTO	TablaDocentes VALUES(@Nombre,@Genero)
		SELECT @Retornado = (SELECT @@IDENTITY)
	END --FIN DE DOCENTE

	ELSE IF @Tipo=3--AGREGRA DATOS DE PAE
	BEGIN
		INSERT INTO	TablaPAES VALUES(@Nombre,@Genero)
		SELECT @Retornado = (SELECT @@IDENTITY)
	END--FIN DEL PAE

	ELSE--AGREGAR DATOS EXTERNO
	BEGIN
		INSERT INTO	TablaExternos VALUES(@Nombre,@Genero)
		SELECT @Retornado = (SELECT @@IDENTITY)
	END--FIN EXTERNOS
END--FIN DEL AS
GO