USE ServicioMedico
GO

IF OBJECT_ID('TablaUsuarios') IS NOT NULL
DROP TABLE TablaUsuarios
GO

CREATE TABLE TablaUsuarios
(
IdUsuario INT IDENTITY(501,1) PRIMARY KEY NOT NULL,
Usuario NVARCHAR(15) UNIQUE NOT NULL,
Contraseña NVARCHAR(15) NOT NULL,
Correo NVARCHAR(70) UNIQUE NOT NULL,
Rol INT NOT NULL,
CONSTRAINT fk_UsuR FOREIGN KEY (Rol) REFERENCES TablaRoles (IDRol)
)
GO

SELECT * FROM TablaUsuarios


/*Tabla Empleados de Prueba*/

CREATE TABLE TablaEmpleados
(
[Cve Persona (Empleados)] INT PRIMARY KEY NOT NULL,
Usuario NVARCHAR(20) UNIQUE NOT NULL,
Contraseña NVARCHAR(20),
Vista SMALLINT NOT NULL,
Rol SMALLINT NOT NULL,
CONSTRAINT fk_PerEmpleado FOREIGN KEY ([Cve Persona (Empleados)]) REFERENCES TablaPersonas (IDPersona) ON DELETE CASCADE,
CONSTRAINT f_RolEmpleado FOREIGN KEY (Rol) REFERENCES TablaRoles (IDRol)
)
GO