USE ServicioMedico
GO

IF OBJECT_ID('CambiosContraseñas') IS NOT NULL
DROP TABLE CambiosContraseñas
GO

CREATE TABLE CambiosContraseñas
(
ID INT NOT NULL,
Nombre NVARCHAR(50) NOT NULL,
Antigua NVARCHAR(15),
Nueva NVARCHAR(15) NOT NULL,
Fecha DATETIME NOT NULL,
Rol NVARCHAR(13)
)
GO