USE ServicioMedico
GO

IF OBJECT_ID('TablaAlumnos') IS NOT NULL
DROP TABLE TablaAlumnos
GO

CREATE TABLE TablaAlumnos
(
[ID Alumno] BIGINT IDENTITY(10013001,1) PRIMARY KEY NOT NULL,
Boleta NVARCHAR(10) NOT NULL,
[Nombre de Alumno] NVARCHAR(50) NOT NULL,
[Genero A] NVARCHAR(9) NOT NULL,
Carrera NVARCHAR(50) NOT NULL,
Grupo NVARCHAR(5) NOT NULL
)
GO

SELECT * FROM TablaAlumnos
GO