USE ServicioMedico
GO

IF OBJECT_ID('tbReportes') IS NOT NULL
DROP TABLE tbReportes
GO

CREATE TABLE tbReportes
(
IdReporte INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Pertenece INT NOT NULL,
FechaReporte DATE NOT NULL,
HombresA INT NOT NULL,
MujeresA INT NOT NULL,
HombresD INT NOT NULL,
MujeresD INT NOT NULL,
HombresP INT NOT NULL,
MujeresP INT NOT NULL,
HombresE INT NOT NULL,
MujeresE INT NOT NULL,
SubtotalH INT NOT NULL,
SubtotalM INT NOT NULL,
Total INT NOT NULL,
CONSTRAINT fk_DocRep FOREIGN KEY (Pertenece) REFERENCES tbDoctores
)
GO

SELECT * FROM tbReportes