USE ServicioMedico
GO

IF OBJECT_ID('tbDocentes') IS NOT NULL
DROP TABLE tbDocentes
GO

CREATE TABLE tbDocentes
(
IdDocente INT PRIMARY KEY NOT NULL,
NumDocente NVARCHAR(20),
RFC_Docente NVARCHAR(15),
CONSTRAINT fk_PacienteD FOREIGN KEY (IdDocente) REFERENCES tbPacientes (IdPaciente),
CONSTRAINT uq_NumDoc UNIQUE(NumDocente),
CONSTRAINT uq_RFC_Doc UNIQUE(RFC_Docente)
)
GO

--TABLA DE PAAES

IF OBJECT_ID('tbPAAES') IS NOT NULL
DROP TABLE tbPAAES
GO

CREATE TABLE tbPAAES
(
IdPAAE INT PRIMARY KEY NOT NULL,
NumPAAE NVARCHAR(20),
RFC_PAAE NVARCHAR(15),
CONSTRAINT fk_PacienteP FOREIGN KEY (IdPAAE) REFERENCES tbPacientes (IdPaciente),
CONSTRAINT uq_NumPaae UNIQUE(NumPAAE),
CONSTRAINT uq_RFC_Paae UNIQUE(RFC_PAAE)
)
GO