USE ServicioMedico
GO

IF OBJECT_ID('TablaDocentes') IS NOT NULL
DROP TABLE TablaDocentes
GO

CREATE TABLE TablaDocentes
(
[ID Docente] BIGINT IDENTITY(20013001,1) PRIMARY KEY NOT NULL,
[Nombre de Docente] NVARCHAR(50) NOT NULL,
[Genero D] NVARCHAR(9)NOT NULL
)
GO

SELECT * FROM TablaDocentes