USE ServicioMedico
GO

IF OBJECT_ID('TablaPAES') IS NOT NULL
DROP TABLE TablaPAES
GO

CREATE TABLE TablaPAES
(
[ID PAE] BIGINT IDENTITY(30013001,1) PRIMARY KEY,
[Nombre de PAE] NVARCHAR(50),
[Genero PAE] NVARCHAR(9)
)
GO

SELECT * FROM TablaPAES