USE ServicioMedico
GO

IF OBJECT_ID('PersonalConsultorio') IS NOT NULL
DROP TABLE PersonalConsultorio
GO

CREATE TABLE PersonalConsultorio
(
ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Nombre NVARCHAR(25) NOT NULL,
Apellido NVARCHAR(25) NOT NULL,
Genero SMALLINT NOT NULL,
CURP_RFC NVARCHAR(18) NOT NULL,
CorreoElectronico NVARCHAR(70) NOT NULL,
UserName NVARCHAR(15),
PassW NVARCHAR (20),
Rol SMALLINT NOT NULL,
Vista SMALLINT NULL,
CONSTRAINT fk_GnrPersonal FOREIGN KEY(Genero) REFERENCES tbGeneros(IdGenero),
CONSTRAINT fk_Rol FOREIGN KEY(Rol) REFERENCES Roles(IdRol),
UNIQUE(CURP_RFC, CorreoElectronico, UserName)
)
GO
